title: Hacker theme
description: Hacker is a theme for GitHub Pages.
show_downloads: true
#google_analytics:
theme: jekyll-theme-hacker

# Event information
event:
  name:        "Example Hacks"
  description: "This is a sample hackathon website that you can use by following instructions on GitHub."
  date:        "5 - 6 August 2022"
  location:    "Holmdel, NJ, United States"

  trust_badge:
    year:   "2017"  # season year
    region: "eu"    # "na" or "eu"
    color:  "white" # "white", "black", "gray", "red", "blue" or "yellow"

  hero:
    links:
      - text: "Apply"
        my_mlh:
          client_id:    "0e2f9fc2921d3ad3e12ae900af630d09382e1b3dc1b5b50de2b01b70ad64dbee"
          redirect_uri: "https://mlh.github.io/mlh-hackathon-boilerplate/success.html"
      - text: "Sponsor"
        href: "mailto:sponsorship@website.com"

  about:
    description: >
      Example Hacks is a hackathon hosted at The University of Example.
      This is your opportunity to describe your event, what to expect, where it is & anything unique to your event.
      Keep it straightforward, don't make it too long.
