theme: jekyll-theme-hacker
show_downloads: false
thumbnail: https://raw.githubusercontent.com/pages-themes/hacker/master/thumbnail.png
#title: jekyll-theme-hacker
#description: Hacker is a Jekyll theme for GitHub Pages
#author: pages-themes
#git: git@github.com:pages-themes/hacker.git
#repository: https://github.com/pages-themes/hacker
